export { default as UiForm } from "#shared/ui/form/form/ui/UiForm.vue";
export { default as UiFormItem } from "#shared/ui/form/form-item/ui/UiFormItem.vue";
export { default as UiInput } from "./input";
export { default as UiButton } from "./button";
export { default as UiIcon } from "./icon";
export { default as UiDialog } from './dialog'
export { default as UiProductCharacteristics } from './product-characteristics'
export { default as UiTabs } from '#shared/ui/tabs/tabs/ui/UiTabs.vue'
export { default as UiTabPane } from '#shared/ui/tabs/tab-pane/ui/UiTabPane.vue'
export { default as UiCheckbox } from '#shared/ui/checkbox/checkbox/ui/UiCheckbox.vue'
