export { default as UiForm } from "#shared/ui/form/form/ui/UiForm.vue";
export { default as UiFormItem } from "#shared/ui/form/form-item/ui/UiFormItem.vue";
export { default as UiInput } from "./input";
export { default as UiButton } from "./button";
export { default as UiIcon } from "./icon";
export { default as UiDialog } from './dialog'
export { default as UiProductCharacteristics } from './product-characteristics'
export { default as UiTabs } from '#shared/ui/tabs/tabs/ui/UiTabs.vue'
export { default as UiTabPane } from '#shared/ui/tabs/tab-pane/ui/UiTabPane.vue'
export { default as UiCheckbox } from '#shared/ui/checkbox/checkbox/ui/UiCheckbox.vue'
export { default as UiBreadcrumbs } from '#shared/ui/breadcrumbs/breadcrumbs/ui/UiBreadcrumbs.vue'
export { default as UiBreadcrumbsItem } from '#shared/ui/breadcrumbs/breadcrumb-item/ui/UiBreadcrumbsItem.vue'
export { default as UiTable } from './table/table/UiTable.vue'
export { default as UiTableBody } from './table/table-body/ui/TableBody.vue'
export { default as UiTableCell } from './table/table-cell/ui/TableCell.vue'
export { default as UiTableHead } from './table/table-head/ui/TableHead.vue'
export { default as UiTableHeader } from './table/table-header/ui/TableHeader.vue'
export { default as UiTableRow } from './table/table-row/ui/TableRow.vue'
export { default as UiTableCaption } from './table/table-caption/ui/TableCaption.vue'
